logging:
  level:
    org.springframework:
      data: info
      security: info
      jta: info
    com.ljwm: debug
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: "log/server.log"
